on:
  workflow_dispatch:

jobs:
  update_animes:
    runs-on: ubuntu-latest
    name: Updates README Anime List
    steps:
      - name: Load Animes & Update README
        uses: glup3/anilist-animes-action@v1.0.0
        with:
          ANILIST_USERNAME: 'glup3'
          HEADER_TITLE: "Glup3's cool awesome Animes"
