on:
  schedule:
    # every week
    - cron: 0 0 * * 0

  workflow_dispatch:

jobs:
  update_animes_kuroo:
    runs-on: ubuntu-latest
    name: Updates kuroo.md Anime List
    steps:
      - uses: actions/checkout@v2
      - uses: glup3/anilist-animes-action@v1.0.3
        with:
          ANILIST_USERNAME: 'Kuroo'
          HEADER_TITLE: "Kuroo's mysterious hidden AniList"
          MARKDOWN_PATH: './users/kuroo.md'
          COMMIT_USERNAME: 'AniBOT'
          COMMIT_EMAIL: 'ani-bot@github.com'
          COMMIT_MESSAGE: 'hehe, watched new animes!'

  update_animes_rejukes:
    runs-on: ubuntu-latest
    name: Updates rejukes.md Anime List
    steps:
      - uses: actions/checkout@v2
      - uses: glup3/anilist-animes-action@v1.0.3
        with:
          ANILIST_USERNAME: 'Rejukes'
          MARKDOWN_PATH: './users/rejukes.md'
